#' Ease of use brms wrapper function for fitting growth models specified by \code{growthSS}
#' 
#' @param ss A list generated by \code{growthSS}.
#' @param iter A number of iterations to sample for each chain. By default half this length is taken as warm-up for the MCMC algorithm. This defaults to 2000.
#' @param cores A number of cores to run in parallel. This defaults to 1 if the "mc.cores" option is not set. Generally this is specified as one core per chain so that the model is fit in parallel.
#' @param chains A number of markov chains to use, this defaults to 4.
#' @param prior A \code{brmsprior} object if \code{growthSS} did not have priors specified. If left NULL (the default) and ss does not contain priors then a warning is issued but the model will still attempt to fit.
#' @param backend A backend for brms to use Stan through. This defaults to use "cmdstanr".
#' @param ... Additional arguments passed to \code{brms::brm}.
#' @keywords Bayesian, brms
#' @return A \code{brmsfit} object, see \code{?`brmsfit-class`} for details.
#' 
#' @examples 
#' 
#' ## Not run:
#' simdf<-growthSim("logistic", n=20, t=25, params = list("A"=c(200,160), "B"=c(13, 11), "C"=c(3, 3.5)))
#' ss<-growthSS(model = "logistic", form=y~time|id/group, sigma="spline", df=simdf, priors = list("A"=130, "B"=12, "C"=3))
#' lapply(ss,class)
#' ss$initfun()
#' fit_test <- fitGrowth(ss, iter = 1000, cores = 2, chains = 2, backend = "cmdstanr",
#'               control = list(adapt_delta = 0.999, max_treedepth = 20)) # options to increase performance
#' ## End(Not run)
#' @export

fitGrowth<-function(ss, iter = 2000, cores = getOption("mc.cores",1), chains = 4, prior=NULL, backend = "cmdstanr", ...){
  if(!"prior" %in% names(ss) && is.null(prior)){
    warning("No prior was specified. Flat priors will be used, this is likely to cause problems in model fitting and yield less accurate results.")
  } else if("prior" %in% names(ss)){
      prior <-ss$prior
    }
  fit<-brms::brm(formula = ss$formula, prior = prior, data = ss$df, family=ss$family,
                 iter = iter, init = ss$initfun, cores = cores, chains = chains, backend=backend, ...)
  return(fit)
}

