#' Hypothesis testing for frequentist \code{fitGrowth} models.
#' 
#' @param ss A list output from \link{growthSS}.
#' @param fit A non-brms model (or list of nlrq models) output from \link{fitGrowth}.
#' @param test_pars A vector of parameters to test in the model. These should be parameters which
#' vary by group in your original model and that you want to test against a null model where they
#' do not vary by group.
#' @keywords hypothesis, nlme, nls, nlrq
#' 
#' @details
#' For nls and nlme models an anova is run and returned as part of a list along with the null model.
#'  For nlrq models several assumptions are made and a likelihood ratio test for each tau 
#'  is run and returned as a list.
#' 
#' 
#' @return A list containing an anova object comparing non-linear growth models and the null model.
#' 
#' @examples 
#' 
#' ## Not run:
#' set.seed(123)
#' simdf<-growthSim("logistic", n=20, t=25,
#'    params = list("A"=c(200,160), "B"=c(13, 11), "C"=c(3, 3.5)))
#' ss<-suppressMessages(growthSS(model = "logistic", form=y~time|id/group,
#'   df=simdf, type="nls"))
#' fit <- fitGrowth(ss)
#' testGrowth(ss, fit, "A")$anova
#' 
#' ## End(Not run)
#' @export

testGrowth<-function(ss, fit, test_pars = "A"){
  if(ss$type %in% c("nls", "nlme")){
    res <- .nlAnovaTest(ss, fit, test_pars = "A")
  } else if(ss$type=="nlrq"){
    res <- .nlrqPseudoLRT(ss, fit, test_pars = "A")
  } else if(ss$type =="brms"){
    stop("Use brms::hypothesis to test hypotheses on brms models")
  } 
  return(res)
}



#' nls and nlme testing function
#' @examples
#' if(FALSE){
#' set.seed(123)
#' logistic_df<-growthSim("logistic", n=20, t=25,
#'                   params = list("A"=c(200,160), "B"=c(13, 11), "C"=c(3, 3.5)))
#' ss<-growthSS(model = "logistic", form=y~time|id/group, 
#'           df=logistic_df, type = "nls")
#' fit <- fitGrowth(ss)
#' .nlsTest(ss, fit, test_pars = "A")$anova
#' }
#' @keywords internal
#' @noRd

.nlAnovaTest <- function(ss, fit, test_pars = "A"){
  #* `Get parameters to vary in comparison model`
  xForm <- as.character(ss$formula)[3]
  rMatches <- gregexpr(".2?\\[", xForm)
  original_grouped_pars <- sub("\\[", "", regmatches(xForm, rMatches)[[1]])
  null_pars = original_grouped_pars[!original_grouped_pars %in% test_pars]
  #* `match call for previous model, updating pars`
  lcall <- as.list(ss$call)
  lcall$pars = null_pars
  lcall$df = ss$df
  new_call <- as.call(lcall)
  #* `rerun growthSS and fitGrowth with updated parameters`
  nullSS <- suppressMessages(eval(new_call))
  nullMod <- fitGrowth(nullSS)
  #* `compare models and return values`
  anv <- stats::anova(nullMod,fit)
  out <- list("anova" = anv, "nullMod"=nullMod)
  return(out)
}

#' pseudo LRT function for nlrq, aiming to use empirical likelihood given more time
#' @param nested_models list of models with the same tau generated by testGrowth
#' @examples
#' if(FALSE){
#' set.seed(123)
#' logistic_df<-growthSim("logistic", n=20, t=25,
#'                   params = list("A"=c(200,160), "B"=c(13, 11), "C"=c(3, 3.5)))
#' ss<-growthSS(model = "logistic", form=y~time|id/group, 
#'           df=logistic_df, type = "nlrq", tau=c(0.25, 0.5, 0.75))
#' fit <- fitGrowth(ss)
#' 
#' .nlrqPseudoLRT(ss, fit, test_pars = "A")
#' }
#' @keywords internal
#' @noRd

.nlrqPseudoLRT <- function(ss, fit, test_pars = "A"){
#* `Get parameters to vary in comparison model`
xForm <- as.character(ss$formula)[3]
rMatches <- gregexpr(".2?\\[", xForm)
original_grouped_pars <- sub("\\[", "", regmatches(xForm, rMatches)[[1]])
null_pars = original_grouped_pars[!original_grouped_pars %in% test_pars]
#* `match call for previous model, updating pars`
lcall <- as.list(ss$call)
lcall$pars = null_pars
lcall$df = ss$df
new_call <- as.call(lcall)
#* `rerun growthSS and fitGrowth with updated parameters`
nullSS <- suppressMessages(eval(new_call))
nullMods <- fitGrowth(nullSS)
#* `arrange models for comparisons`

modsList <- lapply(ss$taus, function(tau) list(fit[[paste0(tau)]], nullMods[[paste0(tau)]]))

res <- lapply(modsList, function(modsPair){
  .nlrq_pseudoLRT(modsPair)
})
return(res)
}














