# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Add mcstan repo
        run: |
          writeLines('options(repos = c(INLA = "https://mc-stan.org/r-packages/", getOption(\"repos\")))', file("~/.Rprofile", "ab"))
        shell: Rscript {0}
        
      - name: Create and populate check.Renviron file
        run: |
          echo R_CHECK_DONTTEST_EXAMPLES=false >> ~/check.Renviron
          echo R_LIBS=/usr/lib/R/site-library >> ~/check.Renviron
        shell: bash
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint
        
      - name: Lint
        run: lintr::lint_package(linters = lintr::linters_with_defaults(
                                           lintr::line_length_linter(length = 105L),
                                           lintr::object_name_linter(styles = c("snake_case", "symbols",
                                                                              "camelCase", "dotted.case",
                                                                              "lowercase", "UPPERCASE")),
                                           return_linter = NULL,
                                           lintr::brace_linter(allow_single_line = TRUE) ) )
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
