# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Add mcstan repo
        run: |
          writeLines('options(repos = c(INLA = "https://mc-stan.org/r-packages/", getOption(\"repos\")))', file("~/.Rprofile", "ab"))
        shell: Rscript {0}
        
      - name: Create and populate check.Renviron file
        run: |
          echo R_CHECK_DONTTEST_EXAMPLES=false >> ~/check.Renviron
          echo R_LIBS=/usr/lib/R/site-library >> ~/check.Renviron
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Build Cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = parallel::detectCores())
        shell: Rscript {0}

      - name: Test coverage
        run: |
          covr::codecov(
            type = c("examples", "tests"),
            combine_types = TRUE,
            quiet = FALSE,
            clean = FALSE,
            line_exclusions = list("R/readpcvjson.R", "R/plsr.R", "R/vipPlot.R"),
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
